FROM python:3.11-slim

WORKDIR /app

# 安装基础依赖
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    net-tools \
    libgl1 \
    libglib2.0-0 \
    adb \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV ANDROID_HOME=/usr/lib/android-sdk

COPY debug_docker_test.py .
COPY config/ config/

CMD ["python", "debug_docker_test.py"]
